### ISSUE TITLE
Problème upload images ou fichiers du wiki

### ISSUE THREAD

**Issue by webafrancois** [YunoHost-Apps/garradin_ynh#11]
L'envoi d'images ou de fichiers dans le Wiki de Garradin fonctionne, mais les fichiers ne sont ensuite pas atteignables.
Cas d'un installation de Garradin via Yunohost_apps dans un sous-domaine.

Exemple ici pour le wiki public : https://asso.servaf.net/
LEs documents et images 
404 Not Found
nginx

En fait, les images ou documents ne sont pas uploadés correctement. Leprocessus ne génère pas d'erreur (l'objet est référencé), mais l'upload du fichier ne fonctionne pas.

Merci.

**Comment by BenoitCier** [comment]
Vieille issue, cela fonctionne actuellement
