### ISSUE TITLE
Mauvais paramètre try_files

### ISSUE THREAD

**Issue by bohwaz** [YunoHost-Apps/garradin_ynh#12]
https://github.com/YunoHost-Apps/garradin_ynh/blob/f1b1b2cb4fc86385148ea3252b71ef1a81d80419/conf/nginx.conf#L16

Je pense qu'il faudrait avoir plutôt :

> try_files $uri $uri/ /_route.php;

Sinon les plugins ne fonctionneront pas. Mais j'avoue que je n'utilise pas nginx donc à tester.

**Comment by cl-parsons** [comment]
Je viens de tester sur yunohost, avec un domaine dédié à garradin.

Avec le plugin de test, effectivement les pages **index.php** et **config.php** du plugin ne sont pas atteignables.

Et malheureusement le fait de rajouter **_route.php** dans les directives : **try_files** , **fastcgi_index** , **index**, n'aide pas à corriger le souci.

**Comment by cl-parsons** [comment]
Voiçi une configuration adéquate (j'ai pris la configuration garradin ynh en base, et nettoyé les lignes inutiles).

[garradin.conf.txt](https://github.com/YunoHost-Apps/garradin_ynh/files/4141358/garradin.conf.txt)

Un conseil pour les futures configuration NGINX : préférer la direction **root** plutôt qu'**alias**.

**Comment by bohwaz** [comment]
Je ne suis pas un expert nginx mais je viens de re-regarder et à mon avis le `try_files $uri $uri/` dans la section sur les fichiers .php fait que les URLs de type `/admin/fiche.php/` fonctionnent alors que bon c'est pas censé être le cas, même si c'est pas grave, je vois pas l'intérêt.

Sinon tu as juste rajouté `index.php` dans le try_files et ça marche ?

**Comment by BenoitCier** [comment]
Solve on current version
