### ISSUE TITLE
This app is still using the skipped/protected/unprotected_uris/regex settings which are now obsolete and deprecated... 

### ISSUE THREAD

**Issue by strasbourgcurieux** [YunoHost-Apps/garradin_ynh#15]
Bonjour,

Voici le message affiché à installation

/!\ Packagers! This app is still using the skipped/protected/unprotected_uris/regex settings which are now obsolete and deprecated... Instead, you should use the new helpers 'ynh_permission_{create,urls,update,delete}' and the 'visitors' group to initialize the public/private access. Check out the documentation at the bottom of yunohost.org/groups_and_permissions to learn how to use the new permission mechanism.
Packagers ! Please do not use a separate php ini file, merge your directives in the pool file instead.
Installing the app 'garradin'…

Cordialement

**Comment by rodinux** [comment]
Ok, with the new upgrade, you will not have anymore the php.ini file. For the message about the skopped/uris/regex settings, I am tryng to fix it, soon...

**Comment by BenoitCier** [comment]
i thinks this issue is fixed?

**Comment by BenoitCier** [comment]
it's fixed
