### ISSUE TITLE
Extensions on Garradin_ynh (Tāima and Réservations)

### ISSUE THREAD

**Issue by JRelland** [YunoHost-Apps/garradin_ynh#41]
Hi, thank you for Garradin on YNH.

I noted that there is no "Extensions à installer" with Garradin_ynh. Only the "Bannière de bienvenue" Extension available.

With Garradin online (1.0.5 [2593b9def3]), there are two extensions available : 
-  Réservations (version 0.5.1) 
-  Tāima - Suivi du temps (version 0.1)  (useful for the "valorisation du bénévolat")

Thank you for any comment on how to get Tāima with Garradin_ynh.

Thank you again, José

**Comment by rodinux** [comment]
Hi, you can do it manually... I have try on a virtual local server, but it seems working.
First connect to your server on ssh with your admin user. Then can do like that :

```bash
$ cd /var/www/garradin/plugins/
$ sudo wget https://fossil.kd2.org/garradin-plugins/uv/taima.tar.gz
$ sudo chown garradin: taima.tar.gz
$ sudo chmod +x taima.tar.gz
```
After you would see Taima extension and could activate it.

**Comment by rodinux** [comment]
Tell us if it works...

**Comment by BenoitCier** [comment]
i test all plugins on ~1.0.3, it's work but we need to install manualy

**Comment by JRelland** [comment]
Thank you for your quick and clear feedback.
Let me see that with our sysadmin :)

**Comment by rodinux** [comment]
> i test all plugins on ~1.0.3, it's work but we need to install manualy
Can you tell me if I need add a script to backup some files when upgrading the app ? The upgrade can perhaps erase the files...

**Comment by BenoitCier** [comment]
all plugins stay on a tar.gz file on /plugins directory, 
When the app is upgrade the new source code don't clear this directory?

**Comment by rodinux** [comment]
I am not sure, for example in the script upgrade,  we have pit a backup for the files squelettes and the association.sql to keep the datas, I don't think the files stay after an upgrade...

**Comment by JRelland** [comment]
Hi, Thank you. your scripts work very well.
Interface very nice.
Thank you again @rodinux .
