### ISSUE TITLE
Impossible to save a search in Comptabilité 

### ISSUE THREAD

**Issue by jrd10** [YunoHost-Apps/garradin_ynh#44]
Hi, thank you for Garradin on YNH.

In Comptabité > Recherche > 9 écritures trouvées pour cette recherche > "Enregistrer cette recherche" Button,

Instead of saving your search, it opens the YNH main page!

This do not open the screen for saving your search.

Even if, from the YNH main page, you try to go back to Garradin, you return to your result, not the page for saving your search.

Thank you for your feedback.

Note : I cannot open Garradin directly by the Garradin administration page. It automatically open the YNH SSO page. 

Thank you for your feedback. jrd10

**Comment by rodinux** [comment]
Hi, I don't have this issue after try it on a local machine for test... It open a page recherche enregistrés (https://domain.tld/garradin/admin/acc/saved_searches.php)
Is your app garradin installed as a public instance ?
Do you have the last version 1.0.6 ? Version available on the testing branch...

**Comment by BenoitCier** [comment]
I reproduce the issue on 1.0.5
I thinks it's a new bug on Garradin not a problem whit yunohost

**Comment by BenoitCier** [comment]
I upgrade to 1.0.6, the problem is fixed
You need to upgrade to the new version (published yesterday)

**Comment by jrd10** [comment]
Hi it works :)
Thank you for this quick update.

Now I can update my searches :) Even to see the previous ones.

Note: I cannot reach directly Garradin on YNH by its own url (https://mydomaine.org/gestion). I am always redirected to our SSO :). Is it possible to have a direct access to the loggin interface ?

Thank you again for your time and Garradin on YNH.
Best regards, jrd10.

**Comment by BenoitCier** [comment]
> Note: I cannot reach directly Garradin on YNH by its own url (https://mydomaine.org/gestion). I am always redirected to our SSO :). Is it possible to have a direct access to the loggin interface ?

The app is public or not? If not you need to be login on the SSO to have acces to the garradin login interface.

**Comment by jrd10** [comment]
Hi,
In fact, we did not have this choice in the installation interface.

In Users > Groups and permissions > Visitors 
I have added the `Garradin (visitor)` permission.

Now it works fine :).

Thank you to have drawn my attention on this.

BR jrdd10

**Comment by BenoitCier** [comment]
> In fact, we did not have this choice in the installation interface.

we have this choice : the last check box 
![image](https://user-images.githubusercontent.com/73591305/109956256-bd488900-7ce3-11eb-9a83-e164bed702ed.png)

**Comment by jrd10** [comment]
Sorry! I did not remember 

This setting does not appear in Applications > Garradin.

The settings with "Users and Groups" seems to me ok :).

Thank you for your time.

**Comment by BenoitCier** [comment]
Exact The app permission are now configure with Users and groups
Issue Close
