### ISSUE TITLE
Mise à jour automatisée

### ISSUE THREAD

**Issue by bohwaz** [YunoHost-Apps/garradin_ynh#67]
Hello,

je signale que depuis la 1.1.15 l'utilisateur peut faire une mise à jour de l'appli depuis l'admin web directement.

si vous ne voulez pas permettre cela, mais forcer les mises à jour en utilisant le paquet yunohost (peut-être plus simple pour vous), il faudra rajouter dans votre config.local.php :

```
const ENABLE_UPGRADES = false;
```

À vous de voir si vous voulez le laisser activé ou non :)

**Comment by bohwaz** [comment]
PS : autre modif, le paquet devient un `.tar.gz`

**Comment by fflorent** [comment]
@rodinux Je pense qu'on peut clore l'issue du coup ? On a fait le nécessaire pour désactiver la mise à jour automatisée.
