### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by rodinux** [YunoHost-Apps/garradin_ynh#68]
### 

*The operation 'Install the 'garradin' app' could not be completed*

### Context

- Hardware: *Public Cloud bought online*
- YunoHost version: *4.3.4.1*
- I have access to my server: *Through SSH *
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*
- Using, or trying to install package version/branch: *1.1.12~ynh1 stable*

### Steps to reproduce

-    ```sh
    sudo yunohost app install garradin
    ```
### Expected behavior

*Simply Garradin installed *

### Logs

https://paste.yunohost.org/raw/yelebihaxe

**Comment by nathanael-h** [comment]
There are conflicts with php7.4* dependencies... :thinking:

**Comment by rodinux** [comment]
I think the problem is with this line: `php7.4-imagick : Breaks: php-imagick (< 3.5.1-2+0~20211115.33+debian10~1.gbp94a5d6~)`

**Comment by rodinux** [comment]
I found solution here: https://forum.yunohost.org/t/lychee-installation-failed/17196/7
I just use `apt policy php-imagick` to see Candidate version
```
php-imagick:
  Installed: 3.4.3-4.1
  Candidate: 3.5.1-2+0~20211115.33+debian10~1.gbp94a5d6
  Version table:
     3.5.1-2+0~20211115.33+debian10~1.gbp94a5d6 500
        500 https://packages.sury.org/php buster/main amd64 Packages
 *** 3.4.3-4.1 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```
Then `apt install php-imagick=3.5.1-2+0~20211115.33+debian10~1.gbp94a5d6 `
